name: stanley_portfolio
description: "Stanley's Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  core:
    path: core

  get: ^4.6.6
  flutter_native_splash: ^2.3.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/img_splash.png
  android_12: