name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter

  main:
    path: ../features/main

  get: ^4.6.6
  package_info_plus: ^5.0.1
  dio: ^5.4.1
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.6.7
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  infinite_scroll_pagination: ^4.0.0
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^2.3.8
  collection: ^1.18.0
  uuid: ^4.4.0
  url_strategy: ^0.3.0
  lottie: ^3.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

flutter:
  assets:
    - ../assets/
    - ../assets/images/
    - ../assets/anim/
