name: main
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

  get: ^4.6.6
  scrollable_positioned_list: ^0.3.8
  animated_visibility: ^0.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
