name: main
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

  get: ^4.6.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
